-- Schema and seed data for Shop Manager

-- Choose the database before running, e.g.:
-- MySQL: CREATE DATABASE shop_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; USE shop_manager;
-- PostgreSQL: CREATE DATABASE shop_manager; \c shop_manager

-- Tables will be generated by Hibernate (hbm2ddl = update). We just insert seed rows.

-- Roles
INSERT INTO role (id, name) VALUES (1, 'ADMIN') ON DUPLICATE KEY UPDATE name = 'ADMIN';
INSERT INTO role (id, name) VALUES (2, 'CASHIER') ON DUPLICATE KEY UPDATE name = 'CASHIER';

-- Users (passwords will be set at first run if not existing)
-- You can alternatively pre-hash and insert.

-- Sample categories
INSERT INTO category (id, name) VALUES (1, 'Boissons') ON DUPLICATE KEY UPDATE name = 'Boissons';
INSERT INTO category (id, name) VALUES (2, 'Snacks') ON DUPLICATE KEY UPDATE name = 'Snacks';

-- Sample products
INSERT INTO product (id, name, price, quantity, category_id) VALUES (1, 'Coca-Cola 33cl', 1.20, 50, 1)
ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), quantity=VALUES(quantity), category_id=VALUES(category_id);
INSERT INTO product (id, name, price, quantity, category_id) VALUES (2, 'Chips Paprika', 1.80, 30, 2)
ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price), quantity=VALUES(quantity), category_id=VALUES(category_id);
